### ISSUE TITLE
CI needed

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/xBOUT-examples#14]
We should run the notebooks regularly (once a month?) to make sure they are still working ...

**Comment by johnomotani** [comment]
(see also https://github.com/boutproject/xBOUT-examples/issues/13#issuecomment-937545091)

Maybe the 'best' time is when there's a release of `xbout`? I'm not sure how to automate nicely though. There is a GHA job already that runs when a release is published, which runs the unit tests and then releases to PyPi. The trouble is that the action only runs after a tag is created - that's not a problem for unit tests because those were already checked for the commit that's being released, but if there are tests only run in the 'publish' job then if they fail you'd have to delete the tag or immediately create another release or something, which is doable but not nice. One compromise might be to add automated tests to the release, and just have a manual process to check the tests before making the release...

**Comment by ZedThree** [comment]
Github lets you mark a release as a "pre-release" -- I wonder if that would be useful here? Or perhaps if the publish job checked the tag for `-rc*`, and only published it if it ran the tests. Then if the release candidate passed, do an actual release. That might even be automated perhaps!

**Comment by johnomotani** [comment]
I've been marking the xBOUT releases as 'pre-release' - it doesn't seem to do much except put a message on the release page!
